name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Publish plugin
        uses: eskatos/gradle-command-action@v1.2.0
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        with:
          arguments: publishPlugins

      - name: Get release version
        run: |
            echo "RELEASE_VERSION=${{ github.ref }}" | sed 's,refs/tags/v,,' >> ${GITHUB_ENV}
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Modify samples version
        run: |
            PLAY_PLUGIN_LINE="id 'org\.gradle\.playframework' version"
            find src/docs/samples -name 'build.gradle*' -type f -exec sed -i "s/${PLAY_PLUGIN_LINE} '\(.*\)'/${PLAY_PLUGIN_LINE} '${RELEASE_VERSION}'/g" {} +
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update sample version to ${{ env.RELEASE_VERSION }}
          branch: master
          file_pattern: src/docs/samples
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
